// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbEPu3fwftSYS6DndIMPsCTt2I-fUkUEI',
    appId: '1:1091218156777:web:e5684993a9884f65c69478',
    messagingSenderId: '1091218156777',
    projectId: 'ikshayu',
    authDomain: 'ikshayu.firebaseapp.com',
    storageBucket: 'ikshayu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI4UYBxNpgkWjbhgDRzo8QydU0Xi7uJgM',
    appId: '1:1091218156777:android:e8ef1fb9a36bf844c69478',
    messagingSenderId: '1091218156777',
    projectId: 'ikshayu',
    storageBucket: 'ikshayu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCsgmoAMCmHAdCP1epuELdw8EYrh_Q7a0',
    appId: '1:1091218156777:ios:cece24c3462d6c6fc69478',
    messagingSenderId: '1091218156777',
    projectId: 'ikshayu',
    storageBucket: 'ikshayu.appspot.com',
    iosClientId: '1091218156777-qlnb47edei8iefkvo4f25hnd1nune4og.apps.googleusercontent.com',
    iosBundleId: 'com.example.ikshayu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCsgmoAMCmHAdCP1epuELdw8EYrh_Q7a0',
    appId: '1:1091218156777:ios:cece24c3462d6c6fc69478',
    messagingSenderId: '1091218156777',
    projectId: 'ikshayu',
    storageBucket: 'ikshayu.appspot.com',
    iosClientId: '1091218156777-qlnb47edei8iefkvo4f25hnd1nune4og.apps.googleusercontent.com',
    iosBundleId: 'com.example.ikshayu',
  );
}
